### PR TITLE
fix imports copied twice

### LINKED ISSUE #354: [Codemod:next/13/replace-next-head] Invalid codemod output
<hr><p> <strong>⚠️⚠️ Please do not include any proprietary code in the issue. ⚠️⚠️</strong> </p><hr><h3>Codemod: next/13/replace-next-head</h3><p><strong>1. Code before transformation (Input for codemod)</strong></p>

```typescript

```

<p><strong>2. Expected code after transformation (Desired output of codemod)</strong></p>

```typescript
// paste code here
```

<p><strong>3. Faulty code obtained after running the current version of the codemod (Actual output of codemod)</strong></p>

```typescript
import { APP_NAME, SEO_IMG_OGIMG_VIDEO, WEBSITE_URL } from "@calcom/lib/constants";
import { useLocale } from "@calcom/lib/hooks/useLocale";
import { APP_NAME, SEO_IMG_OGIMG_VIDEO, WEBSITE_URL } from "@calcom/lib/constants";
import { APP_NAME, SEO_IMG_OGIMG_VIDEO, WEBSITE_URL } from "@calcom/lib/constants";
```

<h3>Additional context</h3><p> Imports were added multiple times in /apps/web/pages/video/[uid].tsx</p><hr>

### PR DESCRIPTION
**Pull request by DmytroHryshyn**
closes #354

### CODE REVIEW

File: next/13/replace-next-head/test.ts [hunk 1]
```diff
@@ -454,6 +454,58 @@ Checkout my React component:
...
+						<meta property="og:image" content={A} />
+						<meta property="twitter:image" content={A} />
+					</Head>
+					</>)
+			}
+		`;
+
+		const [command] = await transform({
+			'/opt/project/pages/a/index.tsx': A_CONTENT,
+			'/opt/project/constants.ts': '',
```
Comment (grzpab) [inline next/13/replace-next-head/test.ts:474]: why is this needed?

Comment (DmytroHryshyn) [reply next/13/replace-next-head/test.ts]: forgot to remove it

**Review by grzpab — APPROVED** [review]
